"use client";
import { Container } from "react-bootstrap";
import styles from "@/assets/styles/termsOfService.module.scss";

export default function TermsOfService() {
  return (
    <main>
      <Container>
        <h1 className="text-center">Terms Of Service</h1>
        <p className={`mt-3 mb-3 ${styles.font_text}`}>
          Effective date: August 4, 2023
          <br />
          Anki Education, LLC. (“us”, “we”, or “our”) operates the&nbsp;
          <a href="https://anki.edu.vn">https://anki.edu.vn</a> website and the
          Anki Education mobile application (the “Service”).
          <br />
          This page informs you of our policies regarding the collection, use,
          and disclosure of personal data when you use our Service and the
          choices you have associated with that data.
          <br />
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, terms used in this Privacy Policy have the same meanings as in
          our Terms and Conditions.
        </p>
        <div>
          <h3 className={`mt-2 ${styles.style_h3}`}>Definitions</h3>
          <h5 className={`${styles.style_h5}`}>Service</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            Service means the&nbsp;
            <a href="https://anki.edu.vn">https://anki.edu.vn</a> website and
            the Anki Education mobile application operated by Anki Education,
            LLC.
          </p>
          <h5 className={`${styles.style_h5}`}>Personal Data</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
          <h5 className={`${styles.style_h5}`}>Usage Data</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </p>
          <h5 className={`${styles.style_h5}`}>Cookies</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            Cookies are small pieces of data stored on your device (computer or
            mobile device).
          </p>
          <h5 className={`${styles.style_h5}`}>Data Controller</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed.
            <br />
            For the purpose of this Privacy Policy, we are a Data Controller of
            your Personal Data.
          </p>
          <h5 className={`${styles.style_h5}`}>
            Data Processors (or Service Providers)
          </h5>
          <p className={`mb-2 ${styles.font_text}`}>
            Data Processor (or Service Provider) means any natural or legal
            person who processes the data on behalf of the Data Controller.
            <br />
            We may use the services of various Service Providers in order to
            process your data more effectively.
          </p>
          <h5 className={`${styles.style_h5}`}>Data Subject (or User)</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            Data Subject is any living individual who is using our Service and
            is the subject of Personal Data.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>
            Information Collection and Use
          </h3>
          <p className={`mb-2 ${styles.font_text}`}>
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
        </div>
        <div>
          <h3 className={`mt-2 ${styles.style_h3}`}>Types of Data Collected</h3>
          <h5 className={`${styles.style_h5}`}>Personal Data</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to:
            <br />
            First name and last name
            <br />
            Email address
            <br />
            Cookies and Usage Data
            <br />
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you.
            <br />
            You may opt out of receiving any, or all, of these communications
            from us by following the unsubscribe link or instructions provided
            in any email we send or by contacting us.
          </p>
          <h5 className={`${styles.style_h5}`}>Usage Data</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            We may also collect information that your browser sends whenever you
            visit our Service or when you access the Service by or through a
            mobile device (“Usage Data”). <br />
            This Usage Data may include information such as your computer’s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data. <br />
            When you access the Service by or through a mobile device, this
            Usage Data may include information such as the type of mobile device
            you use, your mobile device unique ID, the IP address of your mobile
            device, your mobile operating system, the type of mobile Internet
            browser you use, unique device identifiers and other diagnostic
            data.
          </p>
          <h5 className={`${styles.style_h5}`}>Tracking & Cookies Data</h5>
          <p className={`mb-2 ${styles.font_text}`}>
            We use cookies and similar tracking technologies to track the
            activity on our Service and hold certain information.
            <br />
            Cookies are files with small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Tracking technologies also used
            are beacons, tags, and scripts to collect and track information and
            to improve and analyze our Service.
            <br />
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
            <br />
            Examples of Cookies we use:
            <br />
            Session Cookies: We use Session Cookies to operate our Service and
            various settings.
            <br />
            Security Cookies: We use Security Cookies for security purposes.
            <br />
            Preference Cookies: We use Preference Cookies to remember your
            preferences
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Use of Data</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Anki Education, Inc. uses the collected data for various purposes:
            <br />
            To provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information
            <br />
            To detect, prevent and address technical issues
            <br />
            To monitor the usage of our Service
            <br />
            To gather analysis or valuable information so that we can improve
            our Service
            <br />
            To provide customer support
            <br />
            To allow you to participate in interactive features of our Service
            when you choose to do so
            <br />
            To notify you about changes to our Service
            <br />
            To provide and maintain our Service
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>
            Legal Basis for Processing Personal Data Under General Data
            Protection Regulation (GDPR)
          </h3>
          <p className={`mb-2 ${styles.font_text}`}>
            If you are from the European Economic Area (EEA), Anki Education,
            LLC. legal basis for collecting and using the personal information
            described in this Privacy Policy depends on the Personal Data we
            collect and the specific context in which we collect it.
            <br />
            Anki Education, LLC. may process your Personal Data because:
            <br />
            To comply with the law
            <br />
            For payment processing purposes
            <br />
            The processing is in our legitimate interests and it’s not
            overridden by your rights
            <br />
            You have given us permission to do so
            <br />
            We need to perform a contract with you
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Retention of Data</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Anki Education, LLC. will retain your Personal Data only for as long
            as is necessary for the purposes set out in this Privacy Policy. We
            will retain and use your Personal Data to the extent necessary to
            comply with our legal obligations (for example, if we are required
            to retain your data to comply with applicable laws), resolve
            disputes, and enforce our legal agreements and policies.
            <br />
            Anki Education, LLC. will also retain Usage Data for internal
            analysis purposes. Usage Data is generally retained for a shorter
            period of time, except when this data is used to strengthen the
            security or to improve the functionality of our Service, or we are
            legally obligated to retain this data for longer time periods.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Transfer of Data</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Your information, including Personal Data, may be transferred to —
            and maintained on — computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ than those from your jurisdiction. <br />
            If you are located outside the United States and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to the United States and process it there. <br />
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer. <br />
            Anki Education, LLC. will take all steps reasonably necessary to
            ensure that your data is treated securely and in accordance with
            this Privacy Policy and no transfer of your Personal Data will take
            place to an organization or a country unless there are adequate
            controls in place including the security of your data and other
            personal information.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>
            Disclosure of Data Business Transaction
          </h3>
          <p className={`mb-2 ${styles.font_text}`}>
            If Anki Education, LLC. is involved in a merger, acquisition or
            asset sale, your Personal Data may be transferred. We will provide
            notice before your Personal Data is transferred and becomes subject
            to a different Privacy Policy.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>
            Disclosure for Law Enforcement
          </h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Under certain circumstances, Anki Education, LLC. may be required to
            disclose your Personal Data if required to do so by law or in
            response to valid requests by public authorities (e.g. a court or a
            government agency).
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Legal Requirements</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Anki Education, LLC. may disclose your Personal Data in the good
            faith belief that such action is necessary to:
            <br />
            To protect against legal liability
            <br />
            To protect the personal safety of users of the Service or the public
            <br />
            To prevent or investigate possible wrongdoing in connection with the
            Service
            <br />
            To protect and defend the rights or property of Anki Education, LLC.
            <br />
            To comply with a legal obligation
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Security of Data</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            The security of your data is important to us, but remember that no
            method of transmission over the Internet, or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>“Do Not Track” Signals</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            We do not support Do Not Track (“DNT”). Do Not Track is a preference
            you can set in your web browser to inform websites that you do not
            want to be tracked.
            <br />
            You can enable or disable Do Not Track by visiting the Preferences
            or Settings page of your web browser.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>
            Your Data Protection Rights Under General Data Protection Regulation
            (GDPR)
          </h3>
          <p className={`mb-2 ${styles.font_text}`}>
            If you are a resident of the European Economic Area (EEA), you have
            certain data protection rights. Anki Education, LLC. aims to take
            reasonable steps to allow you to correct, amend, delete, or limit
            the use of your Personal Data.
            <br />
            If you wish to be informed what Personal Data we hold about you and
            if you want it to be removed from our systems, please contact us.
            <br />
            In certain circumstances, you have the following data protection
            rights:
            <br />
            <b>The right to withdraw consent:</b> You also have the right to
            withdraw your consent at any time where Anki Education, LLC. relied
            on your consent to process your personal information.
            <br />
            <b>The right to data portability: </b>You have the right to be
            provided with a copy of the information we have on you in a
            structured, machine-readable and commonly used format.
            <br />
            <b>The right of restriction:</b> You have the right to request that
            we restrict the processing of your personal information.
            <br />
            <b>The right to object:</b> You have the right to object to our
            processing of your Personal Data.
            <br />
            <b>The right of rectification:</b> You have the right to have your
            information rectified if that information is inaccurate or
            incomplete.
            <br />
            <b>
              The right to access, update or to delete the information we have
              on you:
            </b>{" "}
            Whenever made possible, you can access, update or request deletion
            of your Personal Data directly within your account settings section.
            If you are unable to perform these actions yourself, please contact
            us to assist you.
            <br />
            Please note that we may ask you to verify your identity before
            responding to such requests.
            <br />
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Service Providers</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            We may employ third party companies and individuals to facilitate
            our Service (“Service Providers”), to provide the Service on our
            behalf, to perform Service-related services or to assist us in
            analyzing how our Service is used.
            <br />
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Analytics</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Google Analytics</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Google Analytics is a web analytics service offered by Google that
            tracks and reports website traffic. Google uses the data collected
            to track and monitor the use of our Service. This data is shared
            with other Google services. Google may use the collected data to
            contextualize and personalize the ads of its own advertising
            network.
            <br />
            For more information on the privacy practices of Google, please
            visit the Google Privacy & Terms web page here.
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Payments</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            We may provide paid products and/or services within the Service. In
            that case, we use third-party services for payment processing (e.g.
            payment processors).
            <br />
            We will not store or collect your payment card details. That
            information is provided directly to our third-party payment
            processors whose use of your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information.
            <br />
            The payment processors we work with are:
            <br />
            Apple Store In-App Payments: Apple Store Privacy Policy
            <br />
            Google Play In-App Payments: Google Play Privacy Policy
            <br />
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>
            Buying in-app purchases(IAP) in our iOS app
          </h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Some in-app purchases are auto-renewable subscription-based IAP
            which in simple terms mean means: <br />
            Payment will be charged to iTunes Account at confirmation of
            purchase <br />
            Subscription automatically renews unless auto-renew is turned off at
            least 24 hours before the end of the current period <br />
            Account will be charged for renewal within 24 hours prior to the end
            of the current period, and identify the cost of the renewal <br />
            Subscriptions may be managed by the user and auto-renewal may be
            turned off by going to the user’s Account Settings after purchase{" "}
            <br />
            Any unused portion of a free trial period, if offered, will be
            forfeited when the user purchases a subscription to that
            publication, where applicable
          </p>
        </div>
        <div>
          <h3 className={`mt-3 ${styles.style_h3}`}>Links to Other Sites</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            Our Service may contain links to other sites that are not operated
            by us. If you click on a third-party link, you will be directed to
            that third party’s site. We strongly advise you to review the
            Privacy Policy of every site you visit. <br />
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third-party sites or
            services.
          </p>
        </div>
        <div className="mb-4">
          <h3 className={`mt-3 ${styles.style_h3}`}>Contact Us</h3>
          <p className={`mb-2 ${styles.font_text}`}>
            If you have any questions about this Privacy Policy, please contact
            us online or by mail at 95 Trung Ta alley, Kham Thien street, Dong
            Da province, Ha Noi city, Vietnam
          </p>
        </div>
      </Container>
    </main>
  );
}
